[project]
name = "steamgridinstaller"
version = "0.0.1"
authors = [
  { name="ocket8888", email="ocket8888@gmail.com" },
]
description = "A small example package"
readme = "README.md"
dependencies = [
	"requests"
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/ocket8888/steamgridinstaller"
Issues = "https://github.com/ocket8888/steamgridinstaller/issues"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project.scripts]
steamgrid = "steamgridinstaller:main"